services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    envVars:
      - key: SECRET_KEY
        generateValue: true
