from .login import UserLoginView
from .login import AdminLoginView
from .category import CategoryView
from .teacher import TeacherView
from .department import DepartmentView
from .student import StudentView
from .equipment import EquipmentView
from .qr import qr_code_view
from .application import ApplicationView
from .history import HistoryView
from .application import UserApplicationView
from .inventory_list import InventoryListView
from .inventory import InventoryView
