import * as React from "react";
import Box from "@mui/material/Box";
import BottomNavigation from "@mui/material/BottomNavigation";
import BottomNavigationAction from "@mui/material/BottomNavigationAction";
import "./footer.css";
import List from "@mdi/react";
import { mdiFormatListBulletedSquare } from "@mdi/js";
import Borrow from "@mdi/react";
import { mdiCartPlus } from "@mdi/js";
import Borrowing from "@mdi/react";
import { mdiPlaylistPlus } from "@mdi/js";
import Logout from "@mdi/react";
import { mdiLogout } from "@mdi/js";
