import * as React from "react";
import { useState } from "react";
import { ErrorMessage } from "@hookform/error-message";
import { TextField } from "@mui/material";
import OutlinedInput from "@mui/material";
import InputAdornment from "@mui/material";
import IconButton from "@mui/material";
import Visibility from "@mui/icons-material";
import VisibilityOff from "@mui/icons-material/VisibilityOff";
import MenuItem from "@mui/material";
import "./user_register.css";
