from .login_serializer import LoginSerializer
from .teacher_serializer import TeacherSerializer
from .category_serializer import CategorySerializer
from .department_serializer import DepartmentSerializer
