from .login_serializer import LoginSerializer
from .teacher_serializer import TeacherSerializer
from .student_serializer import StudentSerializer
from .category_serializer import CategorySerializer
from .department_serializer import DepartmentSerializer
