services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn equipment_management.wsgi:application --bind 0.0.0.0:8000"
    envVars:
      - key: SECRET_KEY
        generateValue: true
