# Generated by Django 5.0 on 2024-06-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='学科名')),
                ('course_year', models.IntegerField(verbose_name='学科年')),
                ('delete_flag', models.BooleanField(default=False, verbose_name='削除フラグ')),
            ],
            options={
                'verbose_name': '学科',
                'verbose_name_plural': '学科',
                'db_table': 'courses',
            },
        ),
    ]
