# Generated by Django 5.0 on 2024-06-19 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_flag',
            field=models.BooleanField(default=models.Value(False), verbose_name='管理者フラグ'),
        ),
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='equipment_management_api.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='delete_flag',
            field=models.BooleanField(default=models.Value(False), verbose_name='削除フラグ'),
        ),
        migrations.AddField(
            model_name='user',
            name='school_year',
            field=models.IntegerField(null=True, verbose_name='学年'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス'),
        ),
    ]
