# Generated by Django 5.0 on 2024-06-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management_api', '0001_initial'),
    ]

    operations = [
      migrations.CreateModel(
        name='Category',
          fields=[
            ('id', models.AutoField(primary_key=True, serialize=False)),
            ('name', models.CharField(max_length=50)),
          ],
          options={
            'verbose_name': 'Category',
            'verbose_name_plural': 'Categories',
            'db_table': 'categories',
          },
      ),
  ]
