# Generated by Django 5.0 on 2024-06-20 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management_api', '0002_user_admin_flag_user_course_id_user_delete_flag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='course',
            new_name='course_id',
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(auto_now_add=True, verbose_name='実施日')),
                ('delete_flag', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '棚卸',
                'verbose_name_plural': '棚卸',
                'db_table': 'inventories',
            },
        ),
    ]
