# Generated by Django 5.0.6 on 2024-07-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management_api', '0003_rename_course_user_course_id_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='delete_flag',
            field=models.BooleanField(default=False, verbose_name='削除フラグ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='admin_flag',
            field=models.BooleanField(default=False, verbose_name='管理者フラグ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='delete_flag',
            field=models.BooleanField(default=False, verbose_name='削除フラグ'),
        ),
    ]
