# Generated by Django 5.0 on 2024-06-24 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management_api', '0005_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_flag', models.BooleanField(db_default=models.Value(False), verbose_name='削除フラグ')),
                ('inventories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_management_api.inventory', verbose_name='棚卸Id')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_management_api.product', verbose_name='備品Id')),
            ],
            options={
                'verbose_name': '棚卸リスト',
                'verbose_name_plural': '棚卸リスト',
                'db_table': 'inventory_lists',
            },
        ),
    ]
