# Generated by Django 5.0 on 2024-07-01 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management_api', '0006_inventorylist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_key', models.CharField(max_length=255)),
                ('loan_date', models.DateField()),
                ('return_date', models.DateField()),
                ('delete_flag', models.BooleanField(db_default=models.Value(False))),
                ('loan_authorizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_authorizations', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_management_api.product')),
                ('return_authorizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_authorizations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '申請',
                'verbose_name_plural': '申請',
                'db_table': 'application',
            },
        ),
    ]
