# Generated by Django 5.0.6 on 2024-07-17 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management_api', '0004_alter_course_delete_flag_alter_user_admin_flag_and_more'),
        ('equipment_management_api', '0007_application'),
    ]

    operations = [
    ]
