# Generated by Django 5.0 on 2024-08-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management_api', '0010_auto_20240820_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='deadline_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='deadline_temp',
        ),
        migrations.AddField(
            model_name='product',
            name='deadline',
            field=models.IntegerField(default=0),
        ),
    ]
