# Generated by Django 5.0 on 2024-08-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management_api', '0011_remove_product_deadline_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ISBN',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
