# Generated by Django 5.0 on 2024-08-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management_api', '0012_alter_product_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ISBN',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
