# Generated by Django 3.2.25 on 2024-08-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management_api', '0013_alter_product_isbn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='application',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inventorylist',
            name='delete_flag',
            field=models.BooleanField(default=False, verbose_name='削除フラグ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='active_flag',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='lost_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
