# Generated by Django 5.0 on 2024-08-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management_api', '0014_auto_20240823_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
