# Generated by Django 5.0 on 2024-08-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management_api', '0016_alter_application_loan_authorizer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='loan_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='return_date',
            field=models.DateField(null=True),
        ),
    ]
